import {
  Student,
  ClassConfig,
  AttendanceRecord,
  ConductRecord,
  FinanceTransaction,
  ClassFeeCampaign,
  ContactMessage,
} from './types';

export const initialClassConfig: ClassConfig = {
  schoolName: 'THPT Nguyễn Văn An',
  teacherName: 'Trần Thị Hương',
  className: '12A1',
  academicYear: '2026–2027',
  slogan: 'Đoàn kết - Chăm ngoan - Quyết tâm đỗ Đại học nguyện vọng 1',
  classList: ['12A1', '12A2', '12A3', '11A1', '10A1'],
};

export const initialStudents: Student[] = [
  {
    id: 'hs-1',
    stt: 1,
    name: 'Nguyễn Văn An',
    dob: '2009-03-15',
    gender: 'Nam',
    phone: '0912 345 678',
    parentName: 'Nguyễn Văn Bình (Bố)',
    parentPhone: '0988 111 222',
    address: 'Số 12, Ngõ 45, Đường Quang Trung, TP. Hà Đông',
    role: 'Lớp trưởng',
    status: 'Đang học',
    notes: 'Học lực Xuất sắc, gương mẫu, tích cực tham gia hoạt động Đoàn',
  },
  {
    id: 'hs-2',
    stt: 2,
    name: 'Trần Thị Bích Ngọc',
    dob: '2009-07-20',
    gender: 'Nữ',
    phone: '0913 456 789',
    parentName: 'Phạm Thị Lan (Mẹ)',
    parentPhone: '0977 222 333',
    address: 'Số 88, Phố Lê Lợi, TP. Hà Đông',
    role: 'Lớp phó',
    status: 'Đang học',
    notes: 'Phụ trách học tập, giải Nhì môn Toán cấp Tỉnh',
  },
  {
    id: 'hs-3',
    stt: 3,
    name: 'Lê Hoàng Nam',
    dob: '2009-01-10',
    gender: 'Nam',
    phone: '0914 567 890',
    parentName: 'Lê Văn Cường (Bố)',
    parentPhone: '0966 333 444',
    address: 'Khu Đô thị Văn Quán, Hà Đông',
    role: 'Bí thư',
    status: 'Đang học',
    notes: 'Năng động, quản lý nề nếp tốt, giỏi thể thao',
  },
  {
    id: 'hs-4',
    stt: 4,
    name: 'Phạm Minh Đức',
    dob: '2009-11-05',
    gender: 'Nam',
    phone: '0915 678 901',
    parentName: 'Phạm Văn Dũng (Bố)',
    parentPhone: '0955 444 555',
    address: 'Số 24, Đường Trần Phú, Hà Đông',
    role: 'Tổ trưởng',
    status: 'Đang học',
    notes: 'Tổ trưởng Tổ 1, cẩn thận, tỉ mỉ',
  },
  {
    id: 'hs-5',
    stt: 5,
    name: 'Đỗ Thảo Nhi',
    dob: '2009-09-18',
    gender: 'Nữ',
    phone: '0916 789 012',
    parentName: 'Ngô Thị Mai (Mẹ)',
    parentPhone: '0944 555 666',
    address: 'Số 102, Đường Tô Hiệu, Hà Đông',
    role: 'Tổ trưởng',
    status: 'Đang học',
    notes: 'Tổ trưởng Tổ 2, khéo tay, phụ trách ban văn nghệ',
  },
  {
    id: 'hs-6',
    stt: 6,
    name: 'Hoàng Gia Huy',
    dob: '2009-04-25',
    gender: 'Nam',
    phone: '0917 890 123',
    parentName: 'Hoàng Văn Hùng (Bố)',
    parentPhone: '0933 666 777',
    address: 'Số 15, Phố Bà Triệu, Hà Đông',
    role: 'Học sinh',
    status: 'Đang học',
    notes: 'Học giỏi môn Tiếng Anh (IELTS 7.5)',
  },
  {
    id: 'hs-7',
    stt: 7,
    name: 'Vũ Quỳnh Anh',
    dob: '2009-08-30',
    gender: 'Nữ',
    phone: '0918 901 234',
    parentName: 'Vũ Thị Hằng (Mẹ)',
    parentPhone: '0922 777 888',
    address: 'Số 56, Nguyễn Trãi, Thanh Xuân',
    role: 'Học sinh',
    status: 'Đang học',
    notes: 'Ngoan ngoãn, viết chữ đẹp, chăm chỉ',
  },
  {
    id: 'hs-8',
    stt: 8,
    name: 'Bùi Quốc Anh',
    dob: '2009-05-12',
    gender: 'Nam',
    phone: '0919 012 345',
    parentName: 'Bùi Văn Tuấn (Bố)',
    parentPhone: '0911 888 999',
    address: 'Số 67, Đường Vạn Phúc, Hà Đông',
    role: 'Học sinh',
    status: 'Đang học',
    notes: 'Thành viên đội tuyển Vật lý trường',
  },
  {
    id: 'hs-9',
    stt: 9,
    name: 'Đinh Phương Linh',
    dob: '2009-12-01',
    gender: 'Nữ',
    phone: '0920 123 456',
    parentName: 'Đinh Văn Thắng (Bố)',
    parentPhone: '0900 999 000',
    address: 'Chung cư Hyundai Hillstate, Hà Đông',
    role: 'Tổ trưởng',
    status: 'Đang học',
    notes: 'Tổ trưởng Tổ 3, điều hành tổ nhiệt tình',
  },
  {
    id: 'hs-10',
    stt: 10,
    name: 'Dương Tuấn Kiệt',
    dob: '2009-02-14',
    gender: 'Nam',
    phone: '0921 234 567',
    parentName: 'Trịnh Thị Liên (Mẹ)',
    parentPhone: '0989 123 789',
    address: 'Số 45, Đường Chiến Thắng, Văn Quán',
    role: 'Học sinh',
    status: 'Đang học',
    notes: 'Cần chú ý tập trung môn Hóa học hơn',
  },
  {
    id: 'hs-11',
    stt: 11,
    name: 'Hà Thị Kim Ngân',
    dob: '2009-06-19',
    gender: 'Nữ',
    phone: '0922 345 678',
    parentName: 'Hà Quang Hải (Bố)',
    parentPhone: '0978 234 890',
    address: 'Số 72, Đường Lê Trọng Tấn, Hà Đông',
    role: 'Học sinh',
    status: 'Đang học',
    notes: 'Chăm học, nộp bài tập đúng hạn',
  },
  {
    id: 'hs-12',
    stt: 12,
    name: 'Lý Quốc Bảo',
    dob: '2009-10-08',
    gender: 'Nam',
    phone: '0923 456 789',
    parentName: 'Lý Văn Phúc (Bố)',
    parentPhone: '0967 345 901',
    address: 'Số 33, Phố Nhuệ Giang, Hà Đông',
    role: 'Tổ trưởng',
    status: 'Đang học',
    notes: 'Tổ trưởng Tổ 4, gương mẫu, hòa đồng',
  },
  {
    id: 'hs-13',
    stt: 13,
    name: 'Mai Thanh Thảo',
    dob: '2009-04-03',
    gender: 'Nữ',
    phone: '0924 567 890',
    parentName: 'Mai Thị Tuyết (Mẹ)',
    parentPhone: '0956 456 012',
    address: 'Số 89, Phùng Hưng, Phúc La, Hà Đông',
    role: 'Học sinh',
    status: 'Đang học',
    notes: 'Có năng khiếu hội họa và trang trí lớp',
  },
  {
    id: 'hs-14',
    stt: 14,
    name: 'Ngô Đăng Khoa',
    dob: '2009-07-14',
    gender: 'Nam',
    phone: '0925 678 901',
    parentName: 'Ngô Xuân Sơn (Bố)',
    parentPhone: '0945 567 123',
    address: 'Số 110, Đường Yên Lộ, Yên Nghĩa',
    role: 'Học sinh',
    status: 'Đang học',
    notes: 'Tích cực phát biểu xây dựng bài trong các tiết tự nhiên',
  },
  {
    id: 'hs-15',
    stt: 15,
    name: 'Phan Bảo Châu',
    dob: '2009-03-22',
    gender: 'Nữ',
    phone: '0926 789 012',
    parentName: 'Phan Văn Nghĩa (Bố)',
    parentPhone: '0934 678 234',
    address: 'Khu Liền kề Văn Phú, Phú La, Hà Đông',
    role: 'Học sinh',
    status: 'Đang học',
    notes: 'Học đều tất cả các môn, ý thức tốt',
  },
  {
    id: 'hs-16',
    stt: 16,
    name: 'Tạ Minh Khang',
    dob: '2009-09-09',
    gender: 'Nam',
    phone: '0927 890 123',
    parentName: 'Đào Thị Hồng (Mẹ)',
    parentPhone: '0923 789 345',
    address: 'Số 14, Ngõ 90, Đường Nguyễn Viết Xuân',
    role: 'Học sinh',
    status: 'Đang học',
    notes: 'Có đôi lần đi muộn đầu tuần do tắc đường, đã tiến bộ',
  },
  {
    id: 'hs-17',
    stt: 17,
    name: 'Võ Thùy Trang',
    dob: '2009-05-28',
    gender: 'Nữ',
    phone: '0928 901 234',
    parentName: 'Võ Minh Tâm (Bố)',
    parentPhone: '0912 890 456',
    address: 'Số 40, Phố Ao Sen, Mộ Lao, Hà Đông',
    role: 'Học sinh',
    status: 'Đang học',
    notes: 'Thành viên ban xung kích nề nếp trường',
  },
  {
    id: 'hs-18',
    stt: 18,
    name: 'Trịnh Tiến Dũng',
    dob: '2009-08-11',
    gender: 'Nam',
    phone: '0929 012 345',
    parentName: 'Trịnh Văn Long (Bố)',
    parentPhone: '0901 901 567',
    address: 'Số 95, Đường Cầu Bươu, Thanh Trì',
    role: 'Học sinh',
    status: 'Đang học',
    notes: 'Ngoan, ham học hỏi, giúp đỡ bạn bè',
  },
  {
    id: 'hs-19',
    stt: 19,
    name: 'Lâm Hải Yến',
    dob: '2009-11-26',
    gender: 'Nữ',
    phone: '0930 123 456',
    parentName: 'Lâm Quang Minh (Bố)',
    parentPhone: '0987 012 678',
    address: 'Tổ dân phố 5, Kiến Hưng, Hà Đông',
    role: 'Học sinh',
    status: 'Đang học',
    notes: 'Có giọng đọc truyền cảm, MC các chương trình của lớp',
  },
  {
    id: 'hs-20',
    stt: 20,
    name: 'Cao Văn Hùng',
    dob: '2009-01-31',
    gender: 'Nam',
    phone: '0931 234 567',
    parentName: 'Cao Thị Kim (Mẹ)',
    parentPhone: '0976 123 789',
    address: 'Khu B La Khê, Hà Đông',
    role: 'Học sinh',
    status: 'Đang học',
    notes: 'Ý thức tự giác tốt, giữ vệ sinh chung',
  },
  {
    id: 'hs-21',
    stt: 21,
    name: 'Nguyễn Diệu Linh',
    dob: '2009-02-17',
    gender: 'Nữ',
    phone: '0932 345 678',
    parentName: 'Nguyễn Văn Hòa (Bố)',
    parentPhone: '0965 234 890',
    address: 'Số 20, Phố Xâm Thị, Hà Đông',
    role: 'Học sinh',
    status: 'Đang học',
    notes: 'Học tốt Ngữ văn và Lịch sử',
  },
  {
    id: 'hs-22',
    stt: 22,
    name: 'Đoàn Thế Anh',
    dob: '2009-10-15',
    gender: 'Nam',
    phone: '0933 456 789',
    parentName: 'Đoàn Văn Chiến (Bố)',
    parentPhone: '0954 345 901',
    address: 'Số 82, Đường Vạn Phúc, Hà Đông',
    role: 'Học sinh',
    status: 'Đang học',
    notes: 'Hăng hái tham gia lao động công ích',
  },
  {
    id: 'hs-23',
    stt: 23,
    name: 'Phùng Mai Anh',
    dob: '2009-06-04',
    gender: 'Nữ',
    phone: '0934 567 890',
    parentName: 'Trần Thị Thu (Mẹ)',
    parentPhone: '0943 456 012',
    address: 'Số 11, Ngõ 108, Đường Quang Trung',
    role: 'Học sinh',
    status: 'Đang học',
    notes: 'Ngoan hiền, hòa đồng với bạn bè',
  },
  {
    id: 'hs-24',
    stt: 24,
    name: 'Lương Tuấn Minh',
    dob: '2009-12-20',
    gender: 'Nam',
    phone: '0935 678 901',
    parentName: 'Lương Đình Trọng (Bố)',
    parentPhone: '0932 567 123',
    address: 'Khu tập thể Dệt May, Phúc La, Hà Đông',
    role: 'Học sinh',
    status: 'Đang học',
    notes: 'Cần rèn luyện tính kiên nhẫn khi làm bài thi',
  },
];

export const initialAttendanceRecords: AttendanceRecord[] = [
  {
    date: '2026-09-16',
    savedAt: '2026-09-16T07:15:00',
    entries: {
      'hs-1': { status: 'present' },
      'hs-2': { status: 'present' },
      'hs-3': { status: 'present' },
      'hs-4': { status: 'present' },
      'hs-5': { status: 'present' },
      'hs-6': { status: 'present' },
      'hs-7': { status: 'present' },
      'hs-8': { status: 'present' },
      'hs-9': { status: 'present' },
      'hs-10': { status: 'late', note: 'Đến muộn 10 phút do hỏng xe' },
      'hs-11': { status: 'present' },
      'hs-12': { status: 'present' },
      'hs-13': { status: 'present' },
      'hs-14': { status: 'present' },
      'hs-15': { status: 'present' },
      'hs-16': { status: 'excused', note: 'Nghỉ ốm sốt có đơn của phụ huynh' },
      'hs-17': { status: 'present' },
      'hs-18': { status: 'present' },
      'hs-19': { status: 'present' },
      'hs-20': { status: 'present' },
      'hs-21': { status: 'present' },
      'hs-22': { status: 'present' },
      'hs-23': { status: 'present' },
      'hs-24': { status: 'present' },
    },
  },
  {
    date: '2026-09-15',
    savedAt: '2026-09-15T07:10:00',
    entries: {
      'hs-1': { status: 'present' },
      'hs-2': { status: 'present' },
      'hs-3': { status: 'present' },
      'hs-4': { status: 'present' },
      'hs-5': { status: 'present' },
      'hs-6': { status: 'present' },
      'hs-7': { status: 'present' },
      'hs-8': { status: 'present' },
      'hs-9': { status: 'present' },
      'hs-10': { status: 'present' },
      'hs-11': { status: 'present' },
      'hs-12': { status: 'present' },
      'hs-13': { status: 'present' },
      'hs-14': { status: 'present' },
      'hs-15': { status: 'present' },
      'hs-16': { status: 'present' },
      'hs-17': { status: 'present' },
      'hs-18': { status: 'present' },
      'hs-19': { status: 'present' },
      'hs-20': { status: 'present' },
      'hs-21': { status: 'present' },
      'hs-22': { status: 'present' },
      'hs-23': { status: 'present' },
      'hs-24': { status: 'present' },
    },
  },
];

export const initialConductRecords: ConductRecord[] = [
  {
    week: 2,
    term: 'Học kỳ 1',
    savedAt: '2026-09-14T17:00:00',
    entries: {
      'hs-1': { score: 98, rating: 'Tốt', note: 'Điều hành lớp xuất sắc, mẫu mực' },
      'hs-2': { score: 96, rating: 'Tốt', note: 'Chăm chỉ hướng dẫn các bạn học bài' },
      'hs-3': { score: 95, rating: 'Tốt', note: 'Tổ chức sinh hoạt chi đoàn sôi nổi' },
      'hs-4': { score: 92, rating: 'Tốt', note: 'Quản lý tổ tốt, đôn đốc vệ sinh' },
      'hs-5': { score: 94, rating: 'Tốt', note: 'Gương mẫu, chuẩn bị tốt lễ khai giảng' },
      'hs-6': { score: 90, rating: 'Tốt', note: 'Tích cực phát biểu trong giờ Anh' },
      'hs-7': { score: 93, rating: 'Tốt', note: 'Chữ đẹp, vở ghi đầy đủ, ngoan' },
      'hs-8': { score: 91, rating: 'Tốt', note: 'Tập trung học tập, không vi phạm' },
      'hs-9': { score: 92, rating: 'Tốt', note: 'Tổ trưởng chu đáo, có trách nhiệm' },
      'hs-10': { score: 82, rating: 'Khá', note: 'Đi muộn 1 lần, cần chú ý giờ giấc', criteria: ['Đi muộn (-5)'] },
      'hs-11': { score: 90, rating: 'Tốt', note: 'Chăm ngoan, lễ phép với thầy cô' },
      'hs-12': { score: 93, rating: 'Tốt', note: 'Tổ trưởng mẫu mực' },
      'hs-13': { score: 88, rating: 'Tốt', note: 'Vẽ báo tường chào mừng năm học mới' },
      'hs-14': { score: 89, rating: 'Tốt', note: 'Tập trung học tập, nộp bài đủ' },
      'hs-15': { score: 92, rating: 'Tốt', note: 'Học lực tốt, nề nếp nghiêm túc' },
      'hs-16': { score: 84, rating: 'Khá', note: 'Nghỉ 1 buổi có phép, học bù bài nghiêm túc' },
      'hs-17': { score: 94, rating: 'Tốt', note: 'Hoàn thành tốt nhiệm vụ trực cờ đỏ' },
      'hs-18': { score: 90, rating: 'Tốt', note: 'Ngoan, tích cực giúp đỡ bạn' },
      'hs-19': { score: 95, rating: 'Tốt', note: 'MC chào cờ đầu tuần đạt khen ngợi' },
      'hs-20': { score: 89, rating: 'Tốt', note: 'Trực nhật sạch sẽ, đúng giờ' },
      'hs-21': { score: 91, rating: 'Tốt', note: 'Ý thức tự giác cao' },
      'hs-22': { score: 87, rating: 'Tốt', note: 'Có tiến bộ trong việc chuẩn bị bài' },
      'hs-23': { score: 90, rating: 'Tốt', note: 'Lễ phép, hòa đồng' },
      'hs-24': { score: 80, rating: 'Khá', note: 'Cần chú ý không nói chuyện riêng giờ Toán', criteria: ['Nói chuyện riêng (-5)'] },
    },
  },
];

export const initialTransactions: FinanceTransaction[] = [
  {
    id: 'tx-1',
    date: '2026-09-05',
    type: 'income',
    amount: 7200000,
    title: 'Thu Quỹ phụ huynh lớp Học kỳ 1',
    category: 'Quỹ lớp',
    person: 'Ban Đại diện Cha mẹ học sinh',
    note: 'Đợt 1 nộp quỹ đầu năm (24/24 học sinh tạm ứng)',
  },
  {
    id: 'tx-2',
    date: '2026-09-06',
    type: 'expense',
    amount: 1250000,
    title: 'Mua hoa và khánh tiết ngày Khai giảng',
    category: 'Sự kiện',
    person: 'Trần Thị Bích Ngọc (Lớp phó)',
    note: 'Lẵng hoa chúc mừng nhà trường và ruy băng lớp',
  },
  {
    id: 'tx-3',
    date: '2026-09-08',
    type: 'expense',
    amount: 680000,
    title: 'Mua nước uống đóng bình và cốc giấy tháng 9',
    category: 'Vật tư',
    person: 'Phạm Minh Đức (Tổ 1)',
    note: '10 bình nước Lavie 19L + 2 lốc cốc dùng 1 lần',
  },
  {
    id: 'tx-4',
    date: '2026-09-10',
    type: 'expense',
    amount: 450000,
    title: 'In tài liệu đề cương ôn tập đầu năm các môn',
    category: 'Học tập',
    person: 'Nguyễn Văn An (Lớp trưởng)',
    note: 'In photo đề cương Toán, Văn, Anh cho cả lớp',
  },
  {
    id: 'tx-5',
    date: '2026-09-12',
    type: 'income',
    amount: 3600000,
    title: 'Thu tiền Áo đồng phục lớp 12A1',
    category: 'Đồng phục',
    person: 'Lê Hoàng Nam (Bí thư)',
    note: '24 học sinh x 150.000đ',
  },
  {
    id: 'tx-6',
    date: '2026-09-14',
    type: 'expense',
    amount: 3600000,
    title: 'Thanh toán tiền may áo đồng phục lớp cho xưởng',
    category: 'Đồng phục',
    person: 'Xưởng May Hà Thành',
    note: '24 áo phông polo có in logo 12A1',
  },
];

export const initialFeeCampaign: ClassFeeCampaign = {
  id: 'fee-1',
  title: 'Quỹ lớp Học kỳ 1 (2026–2027)',
  amountPerStudent: 300000,
  term: 'Học kỳ 1',
  dueDate: '2026-09-30',
  description: 'Chi phí mua tài liệu ôn thi, nước uống, hoạt động ngoại khóa và khen thưởng tuần/tháng',
  studentPayments: {
    'hs-1': { paid: true, paidDate: '2026-09-05', amount: 300000, note: 'Chuyển khoản mẹ' },
    'hs-2': { paid: true, paidDate: '2026-09-05', amount: 300000, note: 'Tiền mặt' },
    'hs-3': { paid: true, paidDate: '2026-09-06', amount: 300000, note: 'Chuyển khoản' },
    'hs-4': { paid: true, paidDate: '2026-09-06', amount: 300000, note: 'Tiền mặt' },
    'hs-5': { paid: true, paidDate: '2026-09-07', amount: 300000, note: 'Chuyển khoản' },
    'hs-6': { paid: true, paidDate: '2026-09-07', amount: 300000, note: 'Tiền mặt' },
    'hs-7': { paid: true, paidDate: '2026-09-08', amount: 300000, note: 'Tiền mặt' },
    'hs-8': { paid: true, paidDate: '2026-09-08', amount: 300000, note: 'Chuyển khoản' },
    'hs-9': { paid: true, paidDate: '2026-09-09', amount: 300000, note: 'Tiền mặt' },
    'hs-10': { paid: false, amount: 300000, note: 'Hẹn nộp ngày 20/09' },
    'hs-11': { paid: true, paidDate: '2026-09-09', amount: 300000, note: 'Tiền mặt' },
    'hs-12': { paid: true, paidDate: '2026-09-10', amount: 300000, note: 'Tiền mặt' },
    'hs-13': { paid: true, paidDate: '2026-09-10', amount: 300000, note: 'Chuyển khoản' },
    'hs-14': { paid: true, paidDate: '2026-09-11', amount: 300000, note: 'Tiền mặt' },
    'hs-15': { paid: true, paidDate: '2026-09-11', amount: 300000, note: 'Chuyển khoản' },
    'hs-16': { paid: false, amount: 300000, note: 'Đang ốm, mẹ xin nộp tuần sau' },
    'hs-17': { paid: true, paidDate: '2026-09-12', amount: 300000, note: 'Tiền mặt' },
    'hs-18': { paid: true, paidDate: '2026-09-12', amount: 300000, note: 'Tiền mặt' },
    'hs-19': { paid: true, paidDate: '2026-09-13', amount: 300000, note: 'Chuyển khoản' },
    'hs-20': { paid: true, paidDate: '2026-09-13', amount: 300000, note: 'Tiền mặt' },
    'hs-21': { paid: true, paidDate: '2026-09-14', amount: 300000, note: 'Chuyển khoản' },
    'hs-22': { paid: true, paidDate: '2026-09-14', amount: 300000, note: 'Tiền mặt' },
    'hs-23': { paid: true, paidDate: '2026-09-15', amount: 300000, note: 'Tiền mặt' },
    'hs-24': { paid: false, amount: 300000, note: 'Chưa nộp' },
  },
};

export const initialContactMessages: ContactMessage[] = [
  {
    id: 'msg-1',
    date: '2026-09-15',
    type: 'broadcast',
    category: 'Thông báo chung',
    title: 'Thông báo Kế hoạch Họp phụ huynh đầu năm học 2026–2027',
    content: 'Kính gửi quý phụ huynh lớp 12A1: Nhà trường và GVCN kính mời quý phụ huynh đến dự buổi Họp CMHS đầu năm vào 8h00 Chủ nhật ngày 20/09/2026 tại phòng học 302 tầng 3. Sự có mặt của quý phụ huynh là nguồn động viên rất lớn cho các con năm cuối cấp!',
    channel: 'Zalo',
    status: 'Đã gửi',
  },
  {
    id: 'msg-2',
    date: '2026-09-14',
    type: 'individual',
    studentId: 'hs-10',
    studentName: 'Dương Tuấn Kiệt',
    category: 'Nhắc nhở',
    title: 'Nhắc nhở về việc đi học đúng giờ và tập trung giờ Hóa',
    content: 'Kính gửi phụ huynh em Tuấn Kiệt: Trong tuần qua em có 1 buổi đi muộn 10 phút và trong tiết Hóa học thầy cô có phản ánh em chưa tập trung chép bài. Nhờ gia đình nhắc nhở em chuẩn bị bài chu đáo trước khi đến lớp ạ.',
    channel: 'Zalo',
    status: 'Đã gửi',
  },
  {
    id: 'msg-3',
    date: '2026-09-12',
    type: 'individual',
    studentId: 'hs-2',
    studentName: 'Trần Thị Bích Ngọc',
    category: 'Khen thưởng',
    title: 'Khen ngợi tinh thần học tập và hỗ trợ lớp',
    content: 'Chúc mừng em Bích Ngọc đã đạt kết quả bài kiểm tra 15 phút Toán 10 điểm tuyệt đối, đồng thời rất nhiệt tình giải đáp thắc mắc bài tập cho các bạn trong tổ!',
    channel: 'SMS',
    status: 'Đã gửi',
  },
  {
    id: 'msg-4',
    date: '2026-09-10',
    type: 'broadcast',
    category: 'Nề nếp',
    title: 'Quy định đồng phục và nền nếp tác phong năm học mới',
    content: 'GVCN xin nhắc nhở toàn thể học sinh: Thứ Hai mặc áo đồng phục trắng sơ vin có thắt cravat/khăn quàng theo quy định; các ngày còn lại mặc áo polo đồng phục lớp hoặc đồng phục trường. Nghiêm cấm sử dụng điện thoại trong giờ học khi chưa có sự cho phép của giáo viên.',
    channel: 'Zalo',
    status: 'Đã gửi',
  },
];
